// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7-aYI341dNy2lAfNHkvEQknNMYu1dVc',
    appId: '1:638359372590:web:29c93346b8a3898c33b0bf',
    messagingSenderId: '638359372590',
    projectId: 'allowancepal-4239e',
    authDomain: 'allowancepal-4239e.firebaseapp.com',
    storageBucket: 'allowancepal-4239e.appspot.com',
    measurementId: 'G-KLNB2XLEJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAfF2cJhAowe81Z-xhUKxydLhBTVoRH38',
    appId: '1:638359372590:android:e80d94ed3d3647f333b0bf',
    messagingSenderId: '638359372590',
    projectId: 'allowancepal-4239e',
    storageBucket: 'allowancepal-4239e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJQojqhxXUQANudLKnC-p_6QyarFP7cYo',
    appId: '1:638359372590:ios:564574578c08b49833b0bf',
    messagingSenderId: '638359372590',
    projectId: 'allowancepal-4239e',
    storageBucket: 'allowancepal-4239e.appspot.com',
    iosClientId: '638359372590-gr3l0frmaq83kcgg0ef94k94a780cb24.apps.googleusercontent.com',
    iosBundleId: 'com.example.allowancepal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJQojqhxXUQANudLKnC-p_6QyarFP7cYo',
    appId: '1:638359372590:ios:dfa6d6275368a41833b0bf',
    messagingSenderId: '638359372590',
    projectId: 'allowancepal-4239e',
    storageBucket: 'allowancepal-4239e.appspot.com',
    iosClientId: '638359372590-2kferebthhkjthffs3enkj6pble4fa94.apps.googleusercontent.com',
    iosBundleId: 'com.example.allowancepal.RunnerTests',
  );
}
